V.ContainerRefreshRate = 3600; -- in seconds

V.I.AddContainerType( 1, "Refridgerator", 6 );
V.I.AddContainerItem( "orange", 2 );
V.I.AddContainerItem( "bananabunch", 8 );
V.I.AddContainerItem( "banana", 2 );
V.I.AddContainerItem( "bottle1", 4 );
V.I.AddContainerItem( "beer1", 4 );
V.I.AddContainerItem( "beer2", 4 );
V.I.AddContainerItem( "whiskey", 4 );
V.I.AddContainerItem( "bottle5", 4 );
V.I.AddContainerItem( "bottle6", 4 );
V.I.AddContainerItem( "brandy", 4 );
V.I.AddContainerItem( "bottle9", 4 );
V.I.AddContainerItem( "milkcarton", 2 );
V.I.AddContainerItem( "milkjug", 4 );
V.I.AddContainerItem( "soda1", 2 );
V.I.AddContainerItem( "soda2", 2 );
V.I.AddContainerItem( "soda3", 2 );
V.I.AddContainerItem( "takeout", 3 );
V.I.AddContainerItem( "water", 2 );
V.I.AddContainerItem( "watermelon", 8 );

V.I.AddContainerType( 2, "Kitchen Cupboard", 6 );
V.I.AddContainerItem( "bandage", 5 );
V.I.AddContainerItem( "bucket", 3 );
V.I.AddContainerItem( "carbattery", 10 );
V.I.AddContainerItem( "drawer", 2 );
V.I.AddContainerItem( "electronicscrap", 5 );
V.I.AddContainerItem( "extinguisher", 3 );
V.I.AddContainerItem( "hammer", 9 );
V.I.AddContainerItem( "painkillers", 3 );
V.I.AddContainerItem( "jarbig", 3 );
V.I.AddContainerItem( "lamp", 6 );
V.I.AddContainerItem( "paint", 7 );
V.I.AddContainerItem( "pipe", 9 );
V.I.AddContainerItem( "paper", 3 );
V.I.AddContainerItem( "plasticbucket", 3 );
V.I.AddContainerItem( "pliers", 5 );
V.I.AddContainerItem( "plug", 6 );
V.I.AddContainerItem( "pot", 9 );
V.I.AddContainerItem( "radio", 10 );
V.I.AddContainerItem( "metal", 5 );
V.I.AddContainerItem( "scrapwood", 5 );
V.I.AddContainerItem( "skull", 64 );
V.I.AddContainerItem( "smallpot", 2 );
V.I.AddContainerItem( "soda1", 4 );
V.I.AddContainerItem( "soda2", 4 );
V.I.AddContainerItem( "soda3", 4 );
V.I.AddContainerItem( "survivalguide", 128 );
V.I.AddContainerItem( "teapot", 2 );
V.I.AddContainerItem( "water", 3 );
V.I.AddContainerItem( "wrench", 9 );

V.I.AddContainerType( 3, "Wardrobe", 5 );
V.I.AddContainerItem( "tshirt", 1 );
V.I.AddContainerItem( "bandage", 6 );
V.I.AddContainerItem( "doll", 16 );
V.I.AddContainerItem( "drawer", 8 );
V.I.AddContainerItem( "electronicscrap", 8 );
V.I.AddContainerItem( "money", 3 );
V.I.AddContainerItem( "paper", 3 );
V.I.AddContainerItem( "photo", 2 );
V.I.AddContainerItem( "pillow", 10 );
V.I.AddContainerItem( "shoe", 2 );
V.I.AddContainerItem( "skull", 64 );
V.I.AddContainerItem( "spine", 64 );
V.I.AddContainerItem( "survivalguide", 128 );

V.I.AddContainerType( 4, "Bathroom Cupboard", 4 );
V.I.AddContainerItem( "toothbrushes", 2 );
V.I.AddContainerItem( "photo", 10 );
V.I.AddContainerItem( "painkillers", 3 );
V.I.AddContainerItem( "jarbig", 3 );
V.I.AddContainerItem( "bandage", 2 );

V.I.AddContainerType( 5, "Scrap Box", 5 );
V.I.AddContainerItem( "plank", 2 );
V.I.AddContainerItem( "carbattery", 10 );
V.I.AddContainerItem( "cinderblock", 10 );
V.I.AddContainerItem( "electronicscrap", 2 );
V.I.AddContainerItem( "lever", 2 );
V.I.AddContainerItem( "metalplate", 2 );
V.I.AddContainerItem( "rebars", 2 );
V.I.AddContainerItem( "metal", 2 );
V.I.AddContainerItem( "scrapwood", 2 );
V.I.AddContainerItem( "tire", 5 );

V.I.AddContainerType( 6, "Toolbox", 2 );
V.I.AddContainerItem( "hammer", 6 );
V.I.AddContainerItem( "pliers", 4 );
V.I.AddContainerItem( "tireiron", 6 );
V.I.AddContainerItem( "wrench", 6 );

V.I.AddContainerType( 7, "Food Stash", 12 );
V.I.AddContainerItem( "orange", 2 );
V.I.AddContainerItem( "bananabunch", 2 );
V.I.AddContainerItem( "banana", 2 );
V.I.AddContainerItem( "bottle1", 4 );
V.I.AddContainerItem( "beer1", 4 );
V.I.AddContainerItem( "beer2", 4 );
V.I.AddContainerItem( "whiskey", 4 );
V.I.AddContainerItem( "bottle5", 4 );
V.I.AddContainerItem( "bottle6", 4 );
V.I.AddContainerItem( "brandy", 4 );
V.I.AddContainerItem( "bottle9", 4 );
V.I.AddContainerItem( "milkcarton", 2 );
V.I.AddContainerItem( "milkjug", 2 );
V.I.AddContainerItem( "soda1", 2 );
V.I.AddContainerItem( "soda2", 2 );
V.I.AddContainerItem( "soda3", 2 );
V.I.AddContainerItem( "takeout", 2 );
V.I.AddContainerItem( "water", 2 );
V.I.AddContainerItem( "watermelon", 2 );

V.I.AddContainerType( 8, "Car", 5 );
V.I.AddContainerItem( "bandage", 4 );
V.I.AddContainerItem( "brokenplank", 4 );
V.I.AddContainerItem( "bucket", 4 );
V.I.AddContainerItem( "carbattery", 2 );
V.I.AddContainerItem( "coffee", 3 );
V.I.AddContainerItem( "electronicscrap", 5 );
V.I.AddContainerItem( "gascan", 4 );
V.I.AddContainerItem( "lever", 4 );
V.I.AddContainerItem( "metalplate", 4 );
V.I.AddContainerItem( "money", 2 );
V.I.AddContainerItem( "paper", 2 );
V.I.AddContainerItem( "photo", 3 );
V.I.AddContainerItem( "pliers", 3 );
V.I.AddContainerItem( "radio", 3 );
V.I.AddContainerItem( "soda1", 2 );
V.I.AddContainerItem( "soda2", 2 );
V.I.AddContainerItem( "soda3", 2 );
V.I.AddContainerItem( "skull", 128 );
V.I.AddContainerItem( "spine", 128 );
V.I.AddContainerItem( "survivalguide", 64 );
V.I.AddContainerItem( "takeout", 4 );
V.I.AddContainerItem( "tincan", 3 );
V.I.AddContainerItem( "tireiron", 3 );
V.I.AddContainerItem( "tire", 3 );
V.I.AddContainerItem( "water", 2 );
V.I.AddContainerItem( "wrench", 3 );

V.I.AddContainerType( 9, "First Aid", 4 );
V.I.AddContainerItem( "bandage", 2 );
V.I.AddContainerItem( "painkillers", 2 );

V.I.AddContainerType( 10, "Vending Machine", 2 );
V.I.AddContainerItem( "soda1", 4 );
V.I.AddContainerItem( "soda2", 4 );
V.I.AddContainerItem( "soda3", 4 );
V.I.AddContainerItem( "water", 4 );
V.I.AddContainerItem( "money", 4 );

V.I.AddContainerType( 11, "Dead Body", 3 );
V.I.AddContainerItem( "axe", 8 );
V.I.AddContainerItem( "banana", 6 );
V.I.AddContainerItem( "bandage", 4 );
V.I.AddContainerItem( "bat", 8 );
V.I.AddContainerItem( "brandy", 6 );
V.I.AddContainerItem( "brokenplank", 6 );
V.I.AddContainerItem( "electronicscrap", 2 );
V.I.AddContainerItem( "hammer", 8 );
V.I.AddContainerItem( "money", 2 );
V.I.AddContainerItem( "orange", 6 );
V.I.AddContainerItem( "painkillers", 4 );
V.I.AddContainerItem( "paper", 4 );
V.I.AddContainerItem( "photo", 8 );
V.I.AddContainerItem( "pipe", 8 );
V.I.AddContainerItem( "pliers", 8 );
V.I.AddContainerItem( "pot", 8 );
V.I.AddContainerItem( "rebars", 8 );
V.I.AddContainerItem( "metal", 2 );
V.I.AddContainerItem( "scrapwood", 2 );
V.I.AddContainerItem( "sledge", 8 );
V.I.AddContainerItem( "soda1", 6 );
V.I.AddContainerItem( "soda2", 6 );
V.I.AddContainerItem( "soda3", 6 );
V.I.AddContainerItem( "survivalguide", 16 );
V.I.AddContainerItem( "tireiron", 8 );
V.I.AddContainerItem( "tshirt", 1 );
V.I.AddContainerItem( "water", 4 );
V.I.AddContainerItem( "wrench", 8 );

V.I.AddContainerType( 12, "Trash", 4 );
V.I.AddContainerItem( "banana", 4 );
V.I.AddContainerItem( "bananabunch", 4 );
V.I.AddContainerItem( "beer1", 4 );
V.I.AddContainerItem( "beer2", 4 );
V.I.AddContainerItem( "brokenplank", 8 );
V.I.AddContainerItem( "carbattery", 8 );
V.I.AddContainerItem( "cinderblock", 4 );
V.I.AddContainerItem( "doll", 4 );
V.I.AddContainerItem( "electronicscrap", 2 );
V.I.AddContainerItem( "fish", 4 );
V.I.AddContainerItem( "lever", 4 );
V.I.AddContainerItem( "metalplate", 2 );
V.I.AddContainerItem( "milkcarton", 4 );
V.I.AddContainerItem( "milkjug", 8 );
V.I.AddContainerItem( "orange", 4 );
V.I.AddContainerItem( "paint", 4 );
V.I.AddContainerItem( "paper", 4 );
V.I.AddContainerItem( "photo", 4 );
V.I.AddContainerItem( "plasticbucket", 4 );
V.I.AddContainerItem( "plug", 4 );
V.I.AddContainerItem( "pot", 8 );
V.I.AddContainerItem( "radio", 4 );
V.I.AddContainerItem( "rebars", 2 );
V.I.AddContainerItem( "rock", 8 );
V.I.AddContainerItem( "metal", 2 );
V.I.AddContainerItem( "scrapwood", 2 );
V.I.AddContainerItem( "shoe", 4 );
V.I.AddContainerItem( "skull", 128 );
V.I.AddContainerItem( "spine", 128 );
V.I.AddContainerItem( "survivalguide", 32 );
V.I.AddContainerItem( "takeout", 4 );
V.I.AddContainerItem( "teapot", 4 );
V.I.AddContainerItem( "tincan", 4 );
V.I.AddContainerItem( "tire", 4 );

V.I.AddContainerType( 13, "Ammo Pile", 2 );
V.I.AddContainerItem( "pistolammo", 32 );
V.I.AddContainerItem( "revolverammo", 32 );
V.I.AddContainerItem( "shotgunammo", 32 );
V.I.AddContainerItem( "rifleammo", 32 );

V.I.AddContainerType( 14, "Dumpster", 2 );
V.I.AddContainerItem( "bleach", 4 );
V.I.AddContainerItem( "bottle1", 4 );
V.I.AddContainerItem( "bottle5", 4 );
V.I.AddContainerItem( "bottle6", 4 );
V.I.AddContainerItem( "bottle9", 4 );
V.I.AddContainerItem( "brokenplank", 8 );
V.I.AddContainerItem( "bucket", 4 );
V.I.AddContainerItem( "cinderblock", 4 );
V.I.AddContainerItem( "doll", 4 );
V.I.AddContainerItem( "drawer", 4 );
V.I.AddContainerItem( "electronicscrap", 2 );
V.I.AddContainerItem( "jarbig", 4 );
V.I.AddContainerItem( "lamp", 4 );
V.I.AddContainerItem( "lampshade", 4 );
V.I.AddContainerItem( "lever", 4 );
V.I.AddContainerItem( "metalplate", 4 );
V.I.AddContainerItem( "milkcarton", 4 );
V.I.AddContainerItem( "paint", 4 );
V.I.AddContainerItem( "paper", 4 );
V.I.AddContainerItem( "photo", 4 );
V.I.AddContainerItem( "pipe", 4 );
V.I.AddContainerItem( "plank", 4 );
V.I.AddContainerItem( "plasticbucket", 4 );
V.I.AddContainerItem( "pliers", 4 );
V.I.AddContainerItem( "plug", 4 );
V.I.AddContainerItem( "pot", 4 );
V.I.AddContainerItem( "rebars", 4 );
V.I.AddContainerItem( "rock", 4 );
V.I.AddContainerItem( "metal", 2 );
V.I.AddContainerItem( "scrapwood", 2 );
V.I.AddContainerItem( "shoe", 4 );
V.I.AddContainerItem( "skull", 128 );
V.I.AddContainerItem( "smallpot", 4 );
V.I.AddContainerItem( "spine", 128 );
V.I.AddContainerItem( "streetsign", 4 );
V.I.AddContainerItem( "takeout", 4 );
V.I.AddContainerItem( "terracotta", 4 );
V.I.AddContainerItem( "tincan", 4 );
V.I.AddContainerItem( "tire", 4 );
V.I.AddContainerItem( "water", 4 );

V.I.AddContainerType( 15, "Cash Register", 1 );
V.I.AddContainerItem( "money", 2 );

V.I.AddContainerType( 16, "Desk", 4 );
V.I.AddContainerItem( "money", 4 );
V.I.AddContainerItem( "drawer", 2 );
V.I.AddContainerItem( "painkillers", 6 );
V.I.AddContainerItem( "paper", 2 );
V.I.AddContainerItem( "survivalguide", 32 );
V.I.AddContainerItem( "electronicscrap", 4 );
V.I.AddContainerItem( "metal", 4 );
V.I.AddContainerItem( "scrapwood", 4 );

V.I.AddContainerType( 17, "Lockers", 4 );
V.I.AddContainerItem( "bandage", 4 );
V.I.AddContainerItem( "electronicscrap", 4 );
V.I.AddContainerItem( "metal", 4 );
V.I.AddContainerItem( "scrapwood", 4 );
V.I.AddContainerItem( "money", 4 );
V.I.AddContainerItem( "paper", 4 );
V.I.AddContainerItem( "photo", 4 );
V.I.AddContainerItem( "shoe", 2 );
V.I.AddContainerItem( "tshirt", 2 );

V.I.AddContainerType( 18, "Filing Cabinet", 4 );
V.I.AddContainerItem( "paper", 2 );
V.I.AddContainerItem( "money", 4 );

V.I.AddContainerType( 19, "Warehouse", 6 );
V.I.AddContainerItem( "axe", 8 );
V.I.AddContainerItem( "bandage", 4 );
V.I.AddContainerItem( "bat", 8 );
V.I.AddContainerItem( "beer1", 4 );
V.I.AddContainerItem( "beer2", 4 );
V.I.AddContainerItem( "bleach", 4 );
V.I.AddContainerItem( "bottle1", 4 );
V.I.AddContainerItem( "bottle5", 4 );
V.I.AddContainerItem( "bottle6", 4 );
V.I.AddContainerItem( "bottle9", 4 );
V.I.AddContainerItem( "brandy", 4 );
V.I.AddContainerItem( "bucket", 4 );
V.I.AddContainerItem( "carbattery", 4 );
V.I.AddContainerItem( "doll", 4 );
V.I.AddContainerItem( "electronicscrap", 2 );
V.I.AddContainerItem( "metal", 2 );
V.I.AddContainerItem( "scrapwood", 2 );
V.I.AddContainerItem( "extinguisher", 4 );
V.I.AddContainerItem( "gascan", 4 );
V.I.AddContainerItem( "hammer", 4 );
V.I.AddContainerItem( "jarbig", 4 );
V.I.AddContainerItem( "lamp", 4 );
V.I.AddContainerItem( "lever", 4 );
V.I.AddContainerItem( "metalplate", 4 );
V.I.AddContainerItem( "money", 8 );
V.I.AddContainerItem( "painkillers", 4 );
V.I.AddContainerItem( "paint", 4 );
V.I.AddContainerItem( "paper", 4 );
V.I.AddContainerItem( "pipe", 4 );
V.I.AddContainerItem( "plasticbucket", 4 );
V.I.AddContainerItem( "pliers", 4 );
V.I.AddContainerItem( "plug", 4 );
V.I.AddContainerItem( "pot", 8 );
V.I.AddContainerItem( "propane", 4 );
V.I.AddContainerItem( "radio", 4 );
V.I.AddContainerItem( "rebars", 4 );
V.I.AddContainerItem( "shoe", 4 );
V.I.AddContainerItem( "sledge", 8 );
V.I.AddContainerItem( "smallpot", 4 );
V.I.AddContainerItem( "survivalguide", 16 );
V.I.AddContainerItem( "teapot", 4 );
V.I.AddContainerItem( "terracotta", 4 );
V.I.AddContainerItem( "tincan", 4 );
V.I.AddContainerItem( "tire", 4 );
V.I.AddContainerItem( "tireiron", 8 );
V.I.AddContainerItem( "toothbrushes", 4 );
V.I.AddContainerItem( "tshirt", 4 );
V.I.AddContainerItem( "whiskey", 4 );
V.I.AddContainerItem( "wrench", 8 );

V.I.AddContainerType( 20, "Cigarette Vending Machine", 1 );
V.I.AddContainerItem( "money", 4 );