V.InsanityText = {
	"name is not a friend.",
	"name will kill you.",
	"name is not to be trusted.",
	"name is wrong.",
	"name is a murderer.",
	"name hates you.",
	"name is broken.",
	"name is dead.",
	"name must die.",
	"name has to go.",
	"name killed us all.",
	"name is a sinner.",
	"name murdered you.",
	"Kill name first.",
	"You can't trust name.",
	"name is one of them.",
	"name is going to hell.",
	"You are in hell.",
	"Humanity is dead.",
	"You are lucky to be dead.",
	"You are a murderer.",
	"You are going to hell.",
	"Life is prison.",
	"Take the easy way out.",
	"Kill yourself.",
	"It's not worth it.",
	"Give up.",
	"The end of days is here.",
	"This isn't real.",
	"Everyone you know is dead.",
	"Better safe than sorry.",
	"Goodbye.",
	"You don't exist.",
	"They will eat you.",
	"You will be one of them.",
	"What's to live for?",
	"Nothing is real.",
	"Too much damage.",
	"You're nothing.",
	"You're unloved.",
	"You're pathetic.",
	"The rivers flow with blood.",
	"There's blood on your hands.",
	"How many have you killed?",
	"How many are left?",
	"There isn't enough food.",
	"What's the death toll?",
	"You can't win.",
	"This is the story of your death.",
	"This is unwinnable.",
	"They won't stop.",
	"Aren't you lonely?",
	"How useless.",
	"Be realistic.",
	"They are watching you.",
	"Were you followed?",
	"Have you been bitten?",
	"There is no more room in hell.",
	"Hell is overflowing.",
	"This is the end."
};