V.ME.AddPropCategory( "Gore" );
V.ME.AddProp( "models/Gibs/HGIBS.mdl" );
V.ME.AddProp( "models/Gibs/HGIBS_rib.mdl" );
V.ME.AddProp( "models/Gibs/HGIBS_scapula.mdl" );
V.ME.AddProp( "models/Gibs/HGIBS_spine.mdl" );

V.ME.AddPropCategory( "Ammo" );
V.ME.AddProp( "models/Items/357ammo.mdl" );
V.ME.AddProp( "models/Items/BoxBuckshot.mdl" );
V.ME.AddProp( "models/Items/BoxMRounds.mdl" );
V.ME.AddProp( "models/Items/BoxSRounds.mdl" );
V.ME.AddProp( "models/Items/ammoCrate_Rockets.mdl" );
V.ME.AddProp( "models/Items/ammocrate_ar2.mdl" );
V.ME.AddProp( "models/Items/ammocrate_grenade.mdl" );
V.ME.AddProp( "models/Items/ammocrate_smg1.mdl" );
V.ME.AddProp( "models/props/de_prodigy/Ammo_Can_01.mdl" );
V.ME.AddProp( "models/props/de_prodigy/Ammo_Can_02.mdl" );
V.ME.AddProp( "models/props/de_prodigy/Ammo_Can_03.mdl" );

V.ME.AddPropCategory( "Boxes" );
V.ME.AddProp( "models/Items/item_item_crate.mdl" );
V.ME.AddProp( "models/props_junk/wood_crate001a.mdl" );
V.ME.AddProp( "models/props_junk/wood_crate001a_damaged.mdl" );
V.ME.AddProp( "models/props_junk/wood_crate001a_damagedmax.mdl" );
V.ME.AddProp( "models/props_junk/wood_crate002a.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box001a.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box001b.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box002a.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box002b.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box003a.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box003b.mdl" );
V.ME.AddProp( "models/props_junk/cardboard_box004a.mdl" );
V.ME.AddProp( "models/props_lab/box01a.mdl" );
V.ME.AddProp( "models/props_lab/box01b.mdl" );
V.ME.AddProp( "models/props/CS_militia/crate_extralargemill.mdl" );
V.ME.AddProp( "models/props/CS_militia/crate_extrasmallmill.mdl" );
V.ME.AddProp( "models/props/CS_militia/crate_stackmill.mdl" );
V.ME.AddProp( "models/props/CS_militia/food_stack.mdl" );
V.ME.AddProp( "models/props/CS_militia/footlocker01_closed.mdl" );
V.ME.AddProp( "models/props/cs_assault/box_stack1.mdl" );
V.ME.AddProp( "models/props/cs_assault/box_stack2.mdl" );
V.ME.AddProp( "models/props/cs_assault/dryer_box.mdl" );
V.ME.AddProp( "models/props/cs_assault/dryer_box2.mdl" );
V.ME.AddProp( "models/props/cs_office/Cardboard_box01.mdl" );
V.ME.AddProp( "models/props/cs_office/Cardboard_box02.mdl" );
V.ME.AddProp( "models/props/cs_office/Cardboard_box03.mdl" );
V.ME.AddProp( "models/props/cs_office/Crates_indoor.mdl" );
V.ME.AddProp( "models/props/de_nuke/crate_extralarge.mdl" );
V.ME.AddProp( "models/props/de_nuke/crate_extrasmall.mdl" );
V.ME.AddProp( "models/props/de_nuke/crate_large.mdl" );
V.ME.AddProp( "models/props/de_nuke/crate_small.mdl" );

V.ME.AddPropCategory( "Vehicles" );
V.ME.AddProp( "models/props/de_piranesi/pi_apc.mdl" );
V.ME.AddProp( "models/props_vehicles/car001a_hatchback.mdl" );
V.ME.AddProp( "models/props_vehicles/car001b_hatchback.mdl" );
V.ME.AddProp( "models/props_vehicles/car002a.mdl" );
V.ME.AddProp( "models/props_vehicles/car002b.mdl" );
V.ME.AddProp( "models/props_vehicles/car003a.mdl" );
V.ME.AddProp( "models/props_vehicles/car003b.mdl" );
V.ME.AddProp( "models/props_vehicles/car004a.mdl" );
V.ME.AddProp( "models/props_vehicles/car004b.mdl" );
V.ME.AddProp( "models/props_vehicles/car005a.mdl" );
V.ME.AddProp( "models/props_vehicles/car005b.mdl" );
V.ME.AddProp( "models/props_vehicles/tanker001a.mdl" );
V.ME.AddProp( "models/props_vehicles/truck001a.mdl" );
V.ME.AddProp( "models/props_vehicles/truck002a_cab.mdl" );
V.ME.AddProp( "models/props_vehicles/truck003a.mdl" );
V.ME.AddProp( "models/props_vehicles/van001a.mdl" );
V.ME.AddProp( "models/props_vehicles/carparts_axel01a.mdl" );
V.ME.AddProp( "models/props_vehicles/carparts_door01a.mdl" );
V.ME.AddProp( "models/props_vehicles/carparts_muffler01a.mdl" );
V.ME.AddProp( "models/props_vehicles/apc_tire001.mdl" );
V.ME.AddProp( "models/props_vehicles/carparts_tire01a.mdl" );
V.ME.AddProp( "models/props_vehicles/carparts_wheel01a.mdl" );
V.ME.AddProp( "models/props_vehicles/tire001a_tractor.mdl" );
V.ME.AddProp( "models/props_vehicles/tire001b_truck.mdl" );
V.ME.AddProp( "models/props_vehicles/tire001c_car.mdl" );
V.ME.AddProp( "models/props/de_nuke/car_nuke.mdl", "models/props/de_nuke/car_nuke_glass.mdl" );
V.ME.AddProp( "models/props/de_nuke/car_nuke_black.mdl", "models/props/de_nuke/car_nuke_glass.mdl" );
V.ME.AddProp( "models/props/de_nuke/car_nuke_red.mdl", "models/props/de_nuke/car_nuke_glass.mdl" );
V.ME.AddProp( "models/props/de_nuke/truck_nuke.mdl", "models/props/de_nuke/truck_nuke_glass.mdl" );
V.ME.AddProp( "models/props/de_train/utility_truck.mdl", "models/props/de_train/utility_truck_windows.mdl" );

V.ME.AddPropCategory( "Seats" );
V.ME.AddProp( "models/props_c17/FurnitureChair001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureCouch001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureCouch002a.mdl" );
V.ME.AddProp( "models/props_c17/bench01a.mdl" );
V.ME.AddProp( "models/props_c17/chair02a.mdl" );
V.ME.AddProp( "models/props_c17/chair_kleiner03a.mdl" );
V.ME.AddProp( "models/props_c17/chair_office01a.mdl" );
V.ME.AddProp( "models/props_c17/chair_stool01a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_Couch01a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_Couch02a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_chair01a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_chair03a.mdl" );
V.ME.AddProp( "models/props_wasteland/controlroom_chair001a.mdl" );
V.ME.AddProp( "models/props/CS_militia/barstool01.mdl" );
V.ME.AddProp( "models/props/CS_militia/couch.mdl" );
V.ME.AddProp( "models/props/cs_office/Chair_office.mdl" );
V.ME.AddProp( "models/props/cs_office/sofa.mdl" );
V.ME.AddProp( "models/props/cs_office/sofa_chair.mdl" );
V.ME.AddProp( "models/props/de_inferno/ChairAntique.mdl" );
V.ME.AddProp( "models/props/de_tides/patio_chair.mdl" );
V.ME.AddProp( "models/props/de_tides/patio_chair2.mdl" );

V.ME.AddPropCategory( "Beds" );
V.ME.AddProp( "models/props_c17/FurnitureBed001a.mdl" );
V.ME.AddProp( "models/props/de_inferno/bed.mdl" );
V.ME.AddProp( "models/props/CS_militia/bunkbed2.mdl", "models/props/CS_militia/bunkbed.mdl" );

V.ME.AddPropCategory( "Personal Storage" );
V.ME.AddProp( "models/props_c17/FurnitureCupboard001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureDrawer001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureDrawer002a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureDrawer003a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureDresser001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureShelf002a.mdl" );
V.ME.AddProp( "models/props_c17/Lockers001a.mdl" );
V.ME.AddProp( "models/props/de_train/Lockers_Long.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_CabinetDrawer01a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_CabinetDrawer02a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_Desk01a.mdl" );
V.ME.AddProp( "models/props_combine/breendesk.mdl" );
V.ME.AddProp( "models/props_wasteland/controlroom_desk001b.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_Vanity01a.mdl" );
V.ME.AddProp( "models/props_interiors/Furniture_shelf01a.mdl" );
V.ME.AddProp( "models/props/cs_havana/bookcase_large.mdl" );
V.ME.AddProp( "models/props/cs_havana/bookcase_small.mdl" );
V.ME.AddProp( "models/props/cs_office/Bookshelf1.mdl" );
V.ME.AddProp( "models/props/cs_office/Bookshelf2.mdl" );
V.ME.AddProp( "models/props/cs_office/Bookshelf3.mdl" );

V.ME.AddPropCategory( "Kitchen" );
V.ME.AddProp( "models/props_c17/furnitureStove001a.mdl" );
V.ME.AddProp( "models/props_interiors/SinkKitchen01a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureFridge001a.mdl" );
V.ME.AddProp( "models/props_interiors/refrigerator01a.mdl" );
V.ME.AddProp( "models/props_wasteland/kitchen_fridge001a.mdl" );
V.ME.AddProp( "models/props_wasteland/kitchen_stove001a.mdl" );
V.ME.AddProp( "models/props_wasteland/kitchen_stove002a.mdl" );

V.ME.AddPropCategory( "Tables" );
V.ME.AddProp( "models/props_c17/FurnitureTable001a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureTable002a.mdl" );
V.ME.AddProp( "models/props_c17/FurnitureTable003a.mdl" );
V.ME.AddProp( "models/props/CS_militia/table_kitchen.mdl" );
V.ME.AddProp( "models/props/CS_militia/table_shed.mdl" );
V.ME.AddProp( "models/props/cs_italy/it_mkt_table2.mdl" );
V.ME.AddProp( "models/props/cs_office/Table_coffee.mdl" );
V.ME.AddProp( "models/props/de_inferno/TableAntique.mdl" );
V.ME.AddProp( "models/props/de_inferno/TableCoffee.mdl" );
V.ME.AddProp( "models/props/de_tides/patio_table.mdl" );
V.ME.AddProp( "models/props/de_tides/patio_table2.mdl" );
V.ME.AddProp( "models/props/de_tides/restaurant_table.mdl" );

V.ME.AddPropCategory( "Barricades / Fences" );
V.ME.AddProp( "models/props_building_details/Storefront_Template001a_Bars.mdl" );
V.ME.AddProp( "models/props_c17/fence01a.mdl" );
V.ME.AddProp( "models/props_c17/fence01b.mdl" );
V.ME.AddProp( "models/props_c17/fence02a.mdl" );
V.ME.AddProp( "models/props_c17/fence02b.mdl" );
V.ME.AddProp( "models/props_c17/fence03a.mdl" );
V.ME.AddProp( "models/props_c17/fence04a.mdl" );
V.ME.AddProp( "models/props_c17/gate_door01a.mdl" );
V.ME.AddProp( "models/props_c17/gate_door02a.mdl" );
V.ME.AddProp( "models/props_trainstation/handrail_64decoration001a.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence001a.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence001b.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence002a.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence002b.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence002c.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence002d.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence002e.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence003a.mdl" );
V.ME.AddProp( "models/props_wasteland/exterior_fence003b.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001a.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001b.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001c.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001d.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001d.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001e.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence001g.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002a.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002b.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002c.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002d.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002e.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence002f.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence003a.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence003b.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence003d.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence003e.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence003f.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence004a.mdl" );
V.ME.AddProp( "models/props_wasteland/interior_fence004b.mdl" );

V.ME.AddPropCategory( "Building Debris" );
V.ME.AddProp( "models/props_debris/barricade_short01a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_short02a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_short03a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_short04a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_tall01a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_tall02a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_tall03a.mdl" );
V.ME.AddProp( "models/props_debris/barricade_tall04a.mdl" );
V.ME.AddProp( "models/props_debris/beam01a.mdl" );
V.ME.AddProp( "models/props_debris/beam01b.mdl" );
V.ME.AddProp( "models/props_debris/beam01c.mdl" );
V.ME.AddProp( "models/props_debris/beam01d.mdl" );
V.ME.AddProp( "models/props_debris/beam01e.mdl" );
V.ME.AddProp( "models/props_debris/broken_floor001a.mdl" );
V.ME.AddProp( "models/props_debris/broken_pile001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk01a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk01b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk01c.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk02a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk02b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk06c.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk06d.mdl" );
V.ME.AddProp( "models/props_debris/concrete_chunk07a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_corner01a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_cornerpile01a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_debris128Pile001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_debris128Pile001b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_debris256Barricade001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_debris256Pile001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_floorpile01a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Floor001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Floor001b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Wall001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Wall001b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Wall001c.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section128Wall002a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section64Floor001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section64Floor001b.mdl" );
V.ME.AddProp( "models/props_debris/concrete_section64Floor001c.mdl" );
V.ME.AddProp( "models/props_debris/concrete_spawnhole001a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_wall01a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_wall02a.mdl" );
V.ME.AddProp( "models/props_debris/concrete_wallpile01a.mdl" );
V.ME.AddProp( "models/props_debris/metal_panel01a.mdl" );
V.ME.AddProp( "models/props_debris/metal_panel02a.mdl" );
V.ME.AddProp( "models/props_debris/metal_panelchunk01a.mdl" );
V.ME.AddProp( "models/props_debris/metal_panelchunk01b.mdl" );
V.ME.AddProp( "models/props_debris/plaster_ceilingpile001a.mdl" );
V.ME.AddProp( "models/props_debris/wood_board06a.mdl" );

V.ME.AddPropCategory( "Garbage Detail" );
V.ME.AddProp( "models/props_junk/garbage128_composite001a.mdl" );
V.ME.AddProp( "models/props_junk/garbage128_composite001b.mdl" );
V.ME.AddProp( "models/props_junk/garbage128_composite001c.mdl" );
V.ME.AddProp( "models/props_junk/garbage128_composite001d.mdl" );
V.ME.AddProp( "models/props_junk/garbage256_composite001a.mdl" );
V.ME.AddProp( "models/props_junk/garbage256_composite001b.mdl" );
V.ME.AddProp( "models/props_junk/garbage256_composite002a.mdl" );
V.ME.AddProp( "models/props_junk/garbage256_composite002b.mdl" );
V.ME.AddProp( "models/props_junk/garbage_carboard001a.mdl" );
V.ME.AddProp( "models/props_junk/garbage_carboard002a.mdl" );

V.ME.AddPropCategory( "Industrial / Construction" );
V.ME.AddProp( "models/props_lab/blastdoor001a.mdl" );
V.ME.AddProp( "models/props_lab/blastdoor001b.mdl" );
V.ME.AddProp( "models/props_lab/blastdoor001c.mdl" );
V.ME.AddProp( "models/props_lab/tpswitch.mdl" );
V.ME.AddProp( "models/props_lab/tpplugholder_single.mdl" );
V.ME.AddProp( "models/props_lab/powerbox01a.mdl" );
V.ME.AddProp( "models/props_lab/powerbox02a.mdl" );
V.ME.AddProp( "models/props_lab/powerbox02b.mdl" );
V.ME.AddProp( "models/props_lab/powerbox02c.mdl" );
V.ME.AddProp( "models/props_lab/powerbox02d.mdl" );
V.ME.AddProp( "models/props_junk/iBeam01a.mdl" );
V.ME.AddProp( "models/props_junk/iBeam01a_cluster01.mdl" );
V.ME.AddProp( "models/props_junk/sawblade001a.mdl" );
V.ME.AddProp( "models/props_junk/wood_pallet001a.mdl" );
V.ME.AddProp( "models/props_citizen_tech/Firetrap_PropaneCanister01a.mdl" );
V.ME.AddProp( "models/props_c17/oildrum001.mdl" );
V.ME.AddProp( "models/props_c17/utilityconnecter006c.mdl" );
V.ME.AddProp( "models/props_c17/substation_transformer01d.mdl" );
V.ME.AddProp( "models/props_c17/substation_circuitbreaker01a.mdl" );
V.ME.AddProp( "models/props_c17/substation_stripebox01a.mdl" );
V.ME.AddProp( "models/props_c17/substation_transformer01a.mdl" );
V.ME.AddProp( "models/props_c17/substation_transformer01b.mdl" );
V.ME.AddProp( "models/props_c17/canister01a.mdl" );
V.ME.AddProp( "models/props_c17/canister02a.mdl" );
V.ME.AddProp( "models/props_c17/canister_propane01a.mdl" );
V.ME.AddProp( "models/props_pipes/concrete_pipe001a.mdl" );
V.ME.AddProp( "models/props_pipes/concrete_pipe001b.mdl" );
V.ME.AddProp( "models/props_pipes/concrete_pipe001c.mdl" );
V.ME.AddProp( "models/props_pipes/concrete_pipe001d.mdl" );
V.ME.AddProp( "models/props_pipes/valvewheel001.mdl" );
V.ME.AddProp( "models/props/CS_militia/sawhorse.mdl" );
V.ME.AddProp( "models/props/cs_assault/ACUnit01.mdl" );
V.ME.AddProp( "models/props/cs_assault/ACUnit02.mdl" );
V.ME.AddProp( "models/props/cs_assault/forklift.mdl" );
V.ME.AddProp( "models/props/de_nuke/cinderblock_stack.mdl" );
V.ME.AddProp( "models/props/de_nuke/PowerPlantTank.mdl" );
V.ME.AddProp( "models/props/de_prodigy/spool.mdl" );
V.ME.AddProp( "models/props/de_prodigy/spoolwire.mdl" );
V.ME.AddProp( "models/props/de_prodigy/concretebags.mdl" );
V.ME.AddProp( "models/props/de_prodigy/concretebags2.mdl" );
V.ME.AddProp( "models/props/de_prodigy/concretebags3.mdl" );
V.ME.AddProp( "models/props/de_prodigy/concretebags4.mdl" );
V.ME.AddProp( "models/props/de_prodigy/pushcart.mdl" );
V.ME.AddProp( "models/props/de_prodigy/tire1.mdl" );
V.ME.AddProp( "models/props/de_prodigy/tire2.mdl" );
V.ME.AddProp( "models/props/de_prodigy/tirestack.mdl" );
V.ME.AddProp( "models/props/de_prodigy/tirestack2.mdl" );
V.ME.AddProp( "models/props/de_prodigy/tirestack3.mdl" );
V.ME.AddProp( "models/props/de_prodigy/transformer.mdl" );
V.ME.AddProp( "models/props/de_train/de_train_signalbox_01.mdl" );

V.ME.AddBedData( "models/props/de_inferno/bed.mdl", Vector( 0, 0, 18 ), Angle() );
V.ME.AddBedData( "models/props_unique/hospital/hospital_bed.mdl", Vector( 0, 0, 22 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_unique/hospital/gurney.mdl", Vector( 0, -5, 33 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_unique/hospital/exam_table.mdl", Vector( 0, 0, 41 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_interiors/bed.mdl", Vector( 0, 0, 30 ), Angle( 0, 270, 0 ) );
V.ME.AddBedData( "models/props_interiors/bed_houseboat.mdl", Vector( 0, 5, 13 ), Angle( 0, 270, 0 ) );
V.ME.AddBedData( "models/props_interiors/bed_motel.mdl", Vector( 0, 5, 29 ), Angle( 0, 270, 0 ) );
V.ME.AddBedData( "models/props_interiors/kids_bed.mdl", Vector( 0, 0, 29 ), Angle( 0, 0, 0 ) );
V.ME.AddBedData( "models/props_equipment/sleeping_bag1.mdl", Vector( 0, 0, 5 ), Angle( 0, 0, 0 ) );
V.ME.AddBedData( "models/props_equipment/sleeping_bag2.mdl", Vector( 0, 0, 5 ), Angle( 0, 0, 0 ) );
V.ME.AddBedData( "models/props_interiors/furniture_couch01a.mdl", Vector( 0, 0, -5 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_interiors/sofa.mdl", Vector( 5, 0, 20 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_interiors/sofa01.mdl", Vector( 5, 0, 17 ), Angle( 0, 90, 0 ) );
V.ME.AddBedData( "models/props_interiors/sofa02.mdl", Vector( 5, 0, 17 ), Angle( 0, 90, 0 ) );

V.ME.AddChairData( "models/props_c17/furniturecouch001a.mdl", Vector( 4, 0, 0 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_c17/furniturecouch002a.mdl", Vector( 0, 0, -3 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/furniture_couch01a.mdl", Vector( 0, 0, -3 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa.mdl", Vector( 5, 0, 22 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa01.mdl", Vector( 4, 0, 20 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa02.mdl", Vector( 4, 0, 20 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_c17/furniturechair001a.mdl", Vector( -3, 0, 0 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_furniture/cafe_barstool1.mdl", Vector( -5, 0, 38 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_furniture/chair2.mdl", Vector( -1, 0, 4 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/bench01a.mdl", Vector( -1, 0, 5 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/bench_subway.mdl", Vector( 0, 5, 24 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_interiors/chair01.mdl", Vector( -4, 0, 2 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/chair_cafeteria.mdl", Vector( -4, 0, 23 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/chair_office2.mdl", Vector( -4, 0, 23 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/chair_thonet.mdl", Vector( 1, 0, 23 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/chairlobby01.mdl", Vector( 0, 1, 26 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_interiors/chairs_airport.mdl", Vector( -3, -6, 23 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_interiors/couch.mdl", Vector( 0, 0, 21 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_interiors/furniture_chair03a.mdl", Vector( -1, 0, 5 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/patio_chair2_white.mdl", Vector( 0, 0, 23 ), Angle( 0, -90, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa_chair.mdl", Vector( 4, 0, 23 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa_chair01.mdl", Vector( 6, 0, 20 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/sofa_chair02.mdl", Vector( 6, 0, 20 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_trainstation/bench_indoor001a.mdl", Vector( -2, 0, 0 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_trainstation/benchoutdoor01a.mdl", Vector( -4, 0, 8 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_wasteland/controlroom_chair001a.mdl", Vector( 0, 0, 0 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/table_picnic.mdl", Vector( -23, 0, 24 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_unique/wheelchair01.mdl", Vector( -5, 0, 23 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_urban/bench001.mdl", Vector( 0, 0, 23 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_urban/plastic_chair001.mdl", Vector( 0, 0, 28 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_urban/bench002.mdl", Vector( 0, -32, 21 ), Angle( 0, -90, 0 ) );
V.ME.AddChairData( "models/props_downtown/booth01.mdl", Vector( -1, 0, 20 ), Angle( 0, 180, 0 ) );
V.ME.AddChairData( "models/props_downtown/booth02.mdl", Vector( -15, 0, 21 ), Angle( 0, -180, 0 ) );
V.ME.AddChairData( "models/props_c17/bench01a.mdl", Vector( -2, 0, 5 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_c17/chair02a.mdl", Vector( 15, -5, 8 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_c17/chair_kleiner03a.mdl", Vector( 7, 0, 45 ), Angle( 0, 180, 0 ) );
V.ME.AddChairData( "models/props_c17/chair_office01a.mdl", Vector( 0, 3, 28 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props_c17/chair_stool01a.mdl", Vector( -3, 0, 40 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/furniture_couch02a.mdl", Vector( 0, 0, -1 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props_interiors/furniture_chair01a.mdl", Vector( -1, 0, 4 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/cs_militia/barstool01.mdl", Vector( -4, 0, 40 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/cs_militia/couch.mdl", Vector( 0, 0, 22 ), Angle( 0, 90, 0 ) );
V.ME.AddChairData( "models/props/cs_office/chair_office.mdl", Vector( 0, 0, 22 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/cs_office/sofa.mdl", Vector( 5, 0, 25 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/cs_office/sofa_chair.mdl", Vector( 2, 0, 25 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/de_inferno/chairantique.mdl", Vector( -5, 0, 21 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/de_tides/patio_chair.mdl", Vector( -3, 0, 26 ), Angle( 0, 0, 0 ) );
V.ME.AddChairData( "models/props/de_tides/patio_chair2.mdl", Vector( 0, 0, 24 ), Angle( 0, -90, 0 ) );

V.ME.AddPropChild( "models/props_vehicles/car_white.mdl", "models/props_vehicles/car_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_69sedan.mdl", "models/props_vehicles/cara_69sedan_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_82hatchback.mdl", "models/props_vehicles/cara_82hatchback_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_82hatchback_wrecked.mdl", "models/props_vehicles/cara_82hatchback_wrecked_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_84sedan.mdl", "models/props_vehicles/cara_84sedan_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_95sedan.mdl", "models/props_vehicles/cara_95sedan_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_95sedan.mdl", "models/props_vehicles/cara_95sedan_glass_alarm.mdl" );
V.ME.AddPropChild( "models/props_vehicles/cara_95sedan_wrecked.mdl", "models/props_vehicles/cara_95sedan_wrecked_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/deliveryvan.mdl", "models/props_vehicles/deliveryvan_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/deliveryvan_armored.mdl", "models/props_vehicles/deliveryvan_armored_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/humvee.mdl", "models/props_vehicles/humvee_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/news_van.mdl", "models/props_vehicles/van_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/police_car.mdl", "models/props_vehicles/police_car_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/police_car_opentrunk.mdl", "models/props_vehicles/police_car_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/semi_truck.mdl", "models/props_vehicles/semi_truck_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/semi_truck3.mdl", "models/props_vehicles/semi_truck_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/taxi_cab.mdl", "models/props_vehicles/police_car_glass.mdl" );
V.ME.AddPropChild( "models/props_vehicles/utility_truck.mdl", "models/props_vehicles/utility_truck_windows.mdl" );
V.ME.AddPropChild( "models/props_vehicles/van.mdl", "models/props_vehicles/van_glass.mdl" );
